### PR TITLE
Clarify curry example by matching the letter r and linking to regex d…

### LINKED ISSUE #372: Explanation of currying clearer if it used real chars instead of white space character class
```
match(/\s+/g, 'hello world');
// [ ' ' ]
```
In https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch4.html
Makes perfect sense if the reader understands regular expressions and that \s+ means one or more spaces.  Consider rewriting with concrete characters. 
Sometimes js programmers don’t know regexes 😱

### PR DESCRIPTION
**Pull request by benshine**
Fixes  #372 , perhaps.

### CODE REVIEW

**Comment by KtorZ** [comment]
On the one hand I am glad to reduce the overall barrier, and in the other hand I am a bit sad that those things have to be explained this much ^^" 

I'll spend some time reviewing the new code and examples in the upcoming days. Thanks for the PR :)

**Comment by benshine** [comment]
I erred towards little bit _too much_ explanation; the only confusing part of each example should be exactly what we’re trying to teach in that example. I almost used `’r’` Instead of the `/r/`  form because  that’s one less language construct to understand, but the _results_ of matching against the string are a little more complicated.

**Comment by KtorZ** [comment]
And I totally agree with your statement :) 
You should give the reader the ability to focus 100% of his attention on the underlying topic and not on some extra quirks of JavaScript or anything else.

**Comment by KtorZ** [comment]
Sorry for the time it took :+1:

**Pull request merged**
