### PR TITLE
Remove offensive phrase from ch3.md

### PR DESCRIPTION
**Pull request by DanielPintilei**

### CODE REVIEW

**Comment by snackycracky** [comment]
offensive phrase ? Could you pleas elaborate on that ?

**Comment by Soreine** [comment]
Related #338 #339

**Comment by DanielPintilei** [comment]
@snackycracky it's about "wrongful use of the name of the Lord your God", the third commandment from the Bible

**Comment by snackycracky** [comment]
I think you are missinterpreting because actually only "god knows what", no?

**Comment by ericpoe** [comment]
I vote for the neutral.

Religiously observant Jews would write "G-d" or "g-d" for similar reasons vowels are removed from the Tetragrammaton. Religiously observant Christians would see it as using the name of God in vain. Atheists and non-religious would see the usage of "god" as odd and would pull the reader away from the text. Non-native speakers might not be familiar with the idiom.

Avoid idioms when possible or go with neutral phrasing.

**Comment by adicirstei** [comment]
Daniel,

You must be kidding. Have you read George Orwell's 1984?

**Comment by snackycracky** [comment]
I am a true believer and I like the name of the lord three times in the book. It makes the book even more divine.

**Comment by ferborva** [comment]
Believers or not, the fact is that this is a change that will leave the sentence in a state of general conformity. 
If the sentence hadn't included the word 'God' or 'god' in it from the beginning, no one would have said anything and the book would be     Just        As        Good.
+1 on my side to end this nonsense conversation that will end in god knows what.

**Comment by snackycracky** [comment]
amen.

**Comment by KtorZ** [comment]
I agree with @Soreine, @ericpoe and @ferborva comments. We can preserve the meaning (and the style) of the sentences while removing "offensive" content. 

Same goes for #338 & #339.

**Comment by bitfrickler** [comment]
Isn't religion supposed to happen at home? As an atheist I am offended by you being offended.

**Comment by KtorZ** [comment]
That's why we keep it out of the book ;)

**Pull request merged**
