### PR TITLE
Remove unnecessary semicolons at EOL in JS examples

### PR DESCRIPTION
**Pull request by jirutka**
Semicolons are really not necessary in well-formated JS, it’s just a syntactic noise. You can read a comprehensive explanation in [Standard](https://github.com/feross/standard) (code-style) [here](https://github.com/feross/standard/blob/master/RULES.md#automatic-semicolon-insertion-asi).

This PR is a direct reaction to #92. Now you can simply choose if you want to consistently add, or remove unnecessary semicolons.

Don’t hesitate to just close this PR without any reaction if you don’t want to remove semicolons, I’m perfectly fine with that! It’s naturally up to you how you choose to format code in your book. However, @chicoxyzzy is right that you should be consistent, if possible.

I’m looking forward to the Part 3 of your wonderful book! :smile_cat:

### CODE REVIEW

**Comment by DrBoolean** [comment]
Hi @jirutka! I fully agree. Someone a few weeks back went and added every semicolon throughout since the es-linters have taken over the world apparently. I appreciate the sentiment and work on this and fully agree with it, but I think I lean toward biting the bullet as something like pasting into jsbin will start spewing red immediately without them.

**Comment by gyzerok** [comment]
I consider this a bad codestyle. Check linters configuration of most huge companies. Airbnb for example.
Especially this is not a codebase, but book. We shouldn't confuse readers.

**Comment by gyzerok** [comment]
And semicolons at the start of the line is the most terrible thing i've ever seen.

**Comment by sadiqevani** [comment]
Yo,

You do understand that those semicolons are not mandatory because the compiler add them automatically by itself. But this doesn't mean you should write those semicolons.

One of the major issues when not adding semicolons is when you return an object:

let say you write something like:

```
function returnObject() {
  return 
{
  name: sadi;
}
}
```

When compiled the following functions will be generated like this:

```
var returnObject = undefined;
returnObject = function () {
  return; // Note the semicolon here.
{
name: sadi;
};
};
function returnObject() {
  return 
{
  name: sadi;
}
}
```

**Comment by kwijibo** [comment]
This seems the same core decision as the issue someone else raised wanting the examples rewritten as ES6.
Should code be written in most cutting-edge best style? Or written to be most widely understood by devs and tools?
It's an interesting question, but to an extent, this is bikeshedding. The important thing is the explanation of the concepts.

**Comment by gyzerok** [comment]
@kwijibo you are trying to compare different things. ES6 is current standard of the language. [JavaScript Standard Style](https://github.com/feross/standard) is just another subjective code-style and nothing more.

**Comment by alex-wilmer** [comment]
Semi-colons as a debate is definitely bike-shedding. Maybe we could make a "style-type" or "ES version" toggle button. I'd be into coding that.

Btw, @DrBoolean keep up the excellent work!

**Comment by DrBoolean** [comment]
Thanks! That'd be really slick, but probably unnecessary. I think ES version might be more than just a toggle since we'd want to take advantage of some extra features and the semi colons are just to appease the masses. I appreciate the thought though!

**Comment by gyzerok** [comment]
@sadiqevani +1

**Pull request closed without merging**
