### PR TITLE
fix missing toArray

### PR DESCRIPTION
**Pull request by eliranmal**
replace a call to `toArray` (which declaration is missing), with a simple `Array.prototype.slice` invocation.

### CODE REVIEW

**Comment by KtorZ** [comment]
What about adding the `toArray` definition instead since it's much more elegant :) ?
There's the `Array.from` method but I think it's ES6+ and we agreed to keep this version of the book compliant with ES5. 

Something like:

```js
const toArray = Function.apply.bind(Array.prototype.slice);
```

Will probably do, or anything you could come up with :)

**Comment by eliranmal** [comment]
@KtorZ seems reasonable, i'll do that. and yes, i'll have it ES5 compliant, as i'm aware of the ES6 separation (and want to help with it!).
i'll just push another commit

**Comment by eliranmal** [comment]
i chose to bind `call`, to have an API similar to slice (usages in the file rely on the ability to slice the array at various positions)

**Comment by KtorZ** [comment]
Sounds fair :)
I am however going to be a bit picky but, what about calling it `toArray` like originally intended ^.^ ?

**Comment by eliranmal** [comment]
oh whoops, that was an honest mistake (i have my own `asArray` in a whole other project..)

**Comment by eliranmal** [comment]
@KtorZ all set :)

**Comment by KtorZ** [comment]
@eliranmal Yup ;) .. I just want to test the code to make sure, for the sake of testing it before merging.

**Comment by KtorZ** [comment]
Merged! :+1:

**Pull request closed without merging**
