### PR TITLE
Added contribution/translation docs

### PR DESCRIPTION
**Pull request by guumaster**
Added some docs on contributions and translations.

### CODE REVIEW

**Comment by DrBoolean** [comment]
@guumaster I'm sorry - i jumped the gun on adding some links. I really want to pull this instead of my changes. I tried checking out your repo, fixing the merge, then pushing, but I didn't have the rights.

**Comment by guumaster** [comment]
You may push to the fork now.

**Comment by guumaster** [comment]
if you prefer, i can rebase and send another PR.

**Comment by DrBoolean** [comment]
Ha yeah. I'm sorry, lots going on at work and i just pushed a silly branch. That'd be great

**Pull request closed without merging**
