### PR TITLE
Ch 03 `const` -> `let`

### PR DESCRIPTION
**Pull request by cuyl**
`minimum` is a mutable variable

### CODE REVIEW

**Comment by KtorZ** [comment]
I think this is actually correct and was wrongly changed to `const` while updating to ES6.
See the beginning of the next paragraph:

> In the impure portion, `checkAge` depends on the mutable variable `minimum` to determine the result.

The idea of that function is to emphasize on the fact that, having `minimum` defined outside of the function scope is potentially impure as minimum could change. Using `const` would prevent that to some extend but it'd be clearer to stick with `let` to leave all confusion out.

**Comment by ptrfrncsmrph** [comment]
Aha, I stand corrected. I figured that the impurity arose from `checkAge` depending on a variable (mutable or not) defined outside of the scope of the function. This continues to be a point of confusion for me in regards to definition of purity.

**Comment by ptrfrncsmrph** [comment]
Aha, I stand corrected. This continues to be a point of confusion for me in regards to definition of purity.

**Comment by cuyl** [comment]
Also change next `minimum `?

```js
 const checkAge = (age) => {
   let minimum = 21;
  // maybe change minimum
   return age >= minimum;
 };
```

It still a pure function.

**Comment by KtorZ** [comment]
The second `const` in the `checkAge` function is fine. We don't need to emphasize on the mutability here.

**Pull request merged**
