### PR TITLE
Typos fixes

### PR DESCRIPTION
**Pull request by legomushroom**
misspelled “safely”
misspelled “implement”

### CODE REVIEW

**Comment by zerkms** [comment]
Oh, please stop creating new PRs. Just commit and push, and github will do everything else for you, automatically.

**Comment by legomushroom** [comment]
@zerkms sorry, I committed and pushed but nothing happened. Probably gui's glitch. Will stick with terminal the next time.

**Comment by zerkms** [comment]
https://github.com/MostlyAdequate/mostly-adequate-guide/pull/172 -- actually everything that should happen happened, all the commits are there.

**Comment by DrBoolean** [comment]
Thanks!

**Pull request merged**
