### PR TITLE
ch9 update Array to use .concat rather than .push

### PR DESCRIPTION
**Pull request by exiadbq**
Explicit usage of Array.prototype.concat() API to enforce pure functions / no mutation in ch9.

### CODE REVIEW

**Comment by safareli** [comment]
This will not work `concat` returns new array and you are not using it's result.

Also as It's wrapped in  `IO` which is used to encapsulate side effects, so looks like it's intended to be impure.

**Comment by exiadbq** [comment]
Oops, I have corrected the return value.  Thanks for that. 
Mutation can be avoided for the array operation to enforce the idea of pure function though.

**Comment by DrBoolean** [comment]
I think the idea was that I was wrapping the push in IO to simulate a side-effect send. I like concat better anyways tho

**Comment by exiadbq** [comment]
I like concat too, also concat can relate to semigroup and monoid... or relatives from afar.. lol.

Should it be merged?

**Comment by safareli** [comment]
I think it's better to add comment before `list.push(email);` indicating that it's "simulating a side-effect" instead of making Pure, because then after some time, someone will ask why are we using IO When it's all pure :d

**Comment by exiadbq** [comment]
Sounds good, let me close this one off.

**Pull request closed without merging**
