### PR TITLE
Polished up some of the text to make it flow more freely, at least in my opinion.

### PR DESCRIPTION
**Pull request by kgish**
Feel free to disagree with me and pick and choose as you see fit.

### CODE REVIEW

**Comment by DrBoolean** [comment]
Dig this. Just going to take a bit to look over. Thanks!

**Comment by kgish** [comment]
Take your time and feel free to use whatever you want. Shall I continue to following chapters of this very fine work of art?

**Comment by kgish** [comment]
Cool!

**Comment by FangfeiAsFey** [comment]
Hi, 


Just take a look at that super awesome stuff!  I think you're gonna love it, check it out <http://santa.zoeynatural.com/e7oof/06>

See you soon, fey_y

**Comment by FangfeiAsFey** [comment]
Dear, 


I've recieved a letter from our old friend,  he  wanted  me  to  share it with you,  just take a  look <http://osvaldo.nathanthomasbrandt.info/e7ax/384>

Best regards, fey_y

**Comment by FangfeiAsFey** [comment]
Greetings, 

Look  at this great and exetremely interesting stuff, it's admired by so  many people, just take  a  look <http://gemma.catherinestronglaw.com/e7qo/4>

Bests, fey_y

**Comment by eenblam** [comment]
@fangfeiasfey your e-mail and/or github has been compromised, and you're pumping out spam pretty quickly. Please correct.

**Pull request merged**
