### PR TITLE
Fix pureLog in support.js to match the implemenation in the book

### PR DESCRIPTION
**Pull request by shaharke**
Specifically the implentation in support.js does not write the string to the console

### CODE REVIEW

**Comment by shaharke** [comment]
Huh... I just realized that `pureLog` is implemented this way so that the exercises will pass...

**Comment by KtorZ** [comment]
Hey! Indeed, the pure log from the support is a bit of a "fake" one; I'd rather fix the exercise wording to reflect that and keep the "testable" implementation here :+1:

**Comment by shaharke** [comment]
Sure. You want me to close this PR and open a new one with a different wording? Happy to help

**Comment by KtorZ** [comment]
So, the support implementation is indeed slightly different because we _need this_ in order to implement the validations in the exercises. Still, it makes sense to have the function actually logging something I suppose ^.^

**Pull request merged**
